package cons

const (
	WINDOW_NAME        = "PASSEBASAS"
	WINDOW_MAIN_WEIGHT = 300
	WINDOW_MAIN_HIGHT  = 300

	BTN_LABEL_CREATE_NEW_CELL = "Create New Log-Pass"

	DIALOG_CREATE_CELL_NAME         = "Enter New Data"
	DIALOG_CREATE_LABEL_PLACEHOLDER = "Enter Name"
	DIALOG_CREATE_LOGIN_PLACEHOLDER = "Enter Login"
	DIALOG_CREATE_PASS_PLACEHOLDER  = "Enter Password"
)
